name: build

on: [push]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: Check DOTNET Cli
        run: dotnet
      - name: Check NPM Cli
        run: npm         